(()=>{'use strict';const root=document.querySelector('.agx');if(!root)return;const hero=root.querySelector('.agx-main-image img'),zoom=root.querySelector('.agx-main-image .agx-zoom'),dialog=root.querySelector('dialog');let opener=null;
function setImage(url,alt){if(hero&&url){hero.src=url;hero.alt=alt||hero.alt;if(zoom)zoom.dataset.full=url;}}
root.addEventListener('click',e=>{const thumb=e.target.closest('[data-gallery]');if(thumb){setImage(thumb.dataset.gallery,thumb.dataset.alt);root.querySelectorAll('[data-gallery]').forEach(b=>b.setAttribute('aria-pressed',String(b===thumb)));}if(e.target.closest('.agx-lightbox-close'))dialog?.close();const play=e.target.closest('[data-embed]');if(play){const f=document.createElement('iframe');f.src=play.dataset.embed;f.title='Product video';f.allow='autoplay; fullscreen; picture-in-picture';f.allowFullscreen=true;play.replaceWith(f);}});
if(dialog){dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>opener?.focus());}
const config=root.querySelector('.agx-config');if(!config)return;let variants=[];try{variants=JSON.parse(config.dataset.variants);}catch{return;}const selected={},price=root.querySelector('.agx-price'),originalPrice=price?.innerHTML,note=config.querySelector('.agx-selection-note');const keys=[...new Set([...config.querySelectorAll('[data-attribute]')].map(b=>b.dataset.attribute))];
config.addEventListener('click',e=>{const b=e.target.closest('[data-attribute]');if(!b)return;selected[b.dataset.attribute]=b.dataset.value;config.querySelectorAll('[data-attribute]').forEach(x=>x.setAttribute('aria-pressed',String(selected[x.dataset.attribute]===x.dataset.value)));const complete=keys.every(k=>Object.hasOwn(selected,k));const match=complete?variants.find(v=>keys.every(k=>!v.attributes[k]||v.attributes[k]===selected[k])):null;if(match){if(price)price.textContent=new DOMParser().parseFromString(match.price,'text/html').documentElement.textContent;setImage(match.image);note.textContent=Object.values(selected).join(' / ')+(match.sku?' · '+match.sku:'')+(match.available?'':' · Availability requires confirmation.');}else{if(price)price.innerHTML=originalPrice;note.textContent=complete?'This combination is not available. Choose another option.':'Select the remaining options to see the matching price.';}});
})();
(function($){if(!$)return;var p=document.querySelector('.agx .agx-price,.agv .agx-price');if(p)p.dataset.orig=p.innerHTML;$(document).on('found_variation','.agx form.variations_form,.agv form.variations_form',function(e,v){var p=document.querySelector('.agx .agx-price,.agv .agx-price');if(p&&v.price_html)p.innerHTML=v.price_html;var img=document.querySelector('.agx-main-image img');if(img&&v.image&&v.image.full_src){img.src=v.image.full_src;img.removeAttribute('srcset');var z=document.querySelector('.agx-main-image .agx-zoom');if(z)z.dataset.full=v.image.full_src;}}).on('reset_data','.agx form.variations_form,.agv form.variations_form',function(){var p=document.querySelector('.agx .agx-price,.agv .agx-price');if(p&&p.dataset.orig)p.innerHTML=p.dataset.orig;});})(window.jQuery);
/* agx lightbox 2 (2026-10): one gallery viewer for hero, project photos, page images and videos.
   Groups: [data-lb-group] ancestor, otherwise the hero/mosaic set or the Elementor body set. Keyboard, swipe, counter, caption. */
(()=>{'use strict';const root=document.querySelector('.agx,.agv');if(!root)return;
const lb=document.createElement('dialog');lb.className='agx-lb';lb.setAttribute('aria-label','Image viewer');
lb.innerHTML='<div class="agx-lb-stage"><img alt=""><div class="agx-lb-video"></div></div><button type="button" class="agx-lb-btn agx-lb-prev" aria-label="Previous">‹</button><button type="button" class="agx-lb-btn agx-lb-next" aria-label="Next">›</button><button type="button" class="agx-lb-close" aria-label="Close">✕</button><div class="agx-lb-bar"><span class="agx-lb-cap"></span><span class="agx-lb-count"></span></div>';
document.body.appendChild(lb);const img=lb.querySelector('img'),vid=lb.querySelector('.agx-lb-video'),cap=lb.querySelector('.agx-lb-cap'),cnt=lb.querySelector('.agx-lb-count');let items=[],idx=0,opener=null;
const isImgLink=a=>/\.(jpe?g|png|webp|gif|avif)(\?|$)/i.test(a.getAttribute('href')||'');
function itemOf(el){if(el.dataset.yt)return{yt:el.dataset.yt,cap:el.dataset.caption||''};if(el.dataset.full)return{src:el.dataset.full,cap:el.dataset.caption||el.querySelector('img')?.alt||''};const i=el.querySelector('img');return{src:el.getAttribute('href'),cap:el.closest('figure')?.querySelector('figcaption')?.textContent.trim()||i?.alt||''};}
function groupOf(el){const g=el.closest('[data-lb-group]');if(g)return[...g.querySelectorAll('[data-full],[data-yt]')];if(el.closest('.agx-vid-grid'))return[...el.closest('.agx-vid-grid').querySelectorAll('[data-yt]')];if(el.closest('.agv-vfeature'))return[...el.closest('.agv-vfeature').querySelectorAll('[data-yt]')];if(el.closest('.agx-el'))return[...root.querySelectorAll('.agx-el a[href]')].filter(isImgLink);const hero=[...root.querySelectorAll('.agx-thumbnails [data-gallery]')];if(el.closest('.agx-main-image')&&hero.length){return hero;}if(el.closest('.agx-mosaic'))return[...root.querySelectorAll('.agx-mosaic [data-full]')];return[el];}
function show(i){idx=(i+items.length)%items.length;const it=items[idx];vid.innerHTML='';if(it.yt){img.hidden=true;vid.hidden=false;const f=document.createElement('iframe');f.src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(it.yt)+'?autoplay=1&rel=0&modestbranding=1';f.title=it.cap||'Video';f.allow='autoplay; fullscreen; picture-in-picture; encrypted-media';f.allowFullscreen=true;vid.appendChild(f);}else{vid.hidden=true;img.hidden=false;img.src=it.src;img.alt=it.cap||'';}cap.textContent=it.cap||'';cnt.textContent=items.length>1?(idx+1)+' / '+items.length:'';lb.classList.toggle('is-single',items.length<2);}
function open(el){const g=groupOf(el);items=g.map(x=>x.dataset&&x.dataset.gallery&&!x.dataset.full?{src:x.dataset.gallery,cap:x.dataset.alt||''}:itemOf(x));let start=g.indexOf(el);if(start<0&&el.closest('.agx-main-image')){const cur=el.dataset.full;start=Math.max(0,items.findIndex(x=>x.src&&cur&&cur.indexOf(x.src.replace(/^https?:\/\/[^/]+/,''))>=0));}if(!items.length)items=[itemOf(el)];opener=el;show(Math.max(0,start));if(!lb.open)lb.showModal();}
function close(){vid.innerHTML='';if(lb.open)lb.close();}
document.addEventListener('click',e=>{const t=e.target.closest('.agx [data-full], .agx [data-yt], .agx .agx-el a[href], .agv [data-full], .agv [data-yt], .agv .agx-el a[href]');if(!t)return;if(t.matches('a[href]')&&!t.dataset.full&&!isImgLink(t))return;e.preventDefault();e.stopImmediatePropagation();open(t);},true);
lb.addEventListener('click',e=>{if(e.target.closest('.agx-lb-prev'))show(idx-1);else if(e.target.closest('.agx-lb-next'))show(idx+1);else if(e.target.closest('.agx-lb-close')||e.target===lb||e.target.classList.contains('agx-lb-stage'))close();});
lb.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(idx-1);else if(e.key==='ArrowRight')show(idx+1);});
lb.addEventListener('close',()=>{if(!lb.open)vid.innerHTML='';opener?.focus();});
let x0=null;lb.addEventListener('touchstart',e=>{x0=e.touches[0].clientX;},{passive:true});lb.addEventListener('touchend',e=>{if(x0===null)return;const dx=e.changedTouches[0].clientX-x0;if(Math.abs(dx)>45&&items.length>1)show(idx+(dx<0?1:-1));x0=null;});
root.addEventListener('click',e=>{const b=e.target.closest('.agx-real-more');if(!b)return;const s=b.closest('.agx-real');const on=!s.classList.contains('is-open');s.classList.toggle('is-open',on);b.setAttribute('aria-expanded',String(on));b.textContent=on?'Show fewer photos':b.dataset.label||b.textContent;});
document.querySelectorAll('.agx-real-more').forEach(b=>b.dataset.label=b.textContent);
})();
/* v2 product page: hero carousel, section nav, mobile buy bar, projects toggle, variation image */
(()=>{'use strict';const root=document.querySelector('.agv');if(!root)return;
const stage=root.querySelector('.agv-stage'),slides=stage?[...stage.querySelectorAll('.agv-slide')]:[],thumbs=[...root.querySelectorAll('.agv-thumbs button')],count=root.querySelector('.agv-count b');let cur=0;
function go(i){if(!slides.length)return;cur=(i+slides.length)%slides.length;stage.scrollTo({left:slides[cur].offsetLeft,behavior:'smooth'});}
function mark(i){cur=i;thumbs.forEach((t,k)=>t.setAttribute('aria-current',String(k===i)));if(count)count.textContent=i+1;const t=thumbs[i];if(t&&t.parentElement)t.parentElement.scrollTo({left:t.offsetLeft-t.parentElement.clientWidth/2+t.clientWidth/2,behavior:'smooth'});
 const im=slides[i]&&slides[i].querySelector('img');[slides[i+1],slides[i-1]].forEach(s=>{const x=s&&s.querySelector('img');if(x&&x.loading==='lazy')x.loading='eager';});}
if(stage){let tm;stage.addEventListener('scroll',()=>{clearTimeout(tm);tm=setTimeout(()=>{const i=Math.round(stage.scrollLeft/stage.clientWidth);if(i!==cur)mark(i);},60);},{passive:true});
 root.querySelector('.agv-prev')?.addEventListener('click',()=>go(cur-1));root.querySelector('.agv-next')?.addEventListener('click',()=>go(cur+1));
 thumbs.forEach((t,k)=>t.addEventListener('click',()=>go(k)));stage.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(cur+1);if(e.key==='ArrowLeft')go(cur-1);});}
// section nav highlight
const links=[...root.querySelectorAll('.agv-nav a[href^="#agv-"]:not(.agv-nav-cta)')];const secs=links.map(a=>document.getElementById(a.getAttribute('href').slice(1))).filter(Boolean);
if('IntersectionObserver'in window&&secs.length){const io=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('is-on',a.getAttribute('href')==='#'+e.target.id));}});},{rootMargin:'-45% 0px -50% 0px'});secs.forEach(s=>io.observe(s));}
// mobile buy bar: visible once the buy panel has scrolled away, hidden near the closing section
const bar=root.querySelector('.agv-bar'),buy=document.getElementById('agv-buy'),close=root.querySelector('.agv-close');
if(bar&&buy&&'IntersectionObserver'in window){let buyOut=false,closeIn=false;const upd=()=>{const on=buyOut&&!closeIn;bar.classList.toggle('is-on',on);bar.setAttribute('aria-hidden',String(!on));bar.querySelector('a').tabIndex=on?0:-1;};
 new IntersectionObserver(([e])=>{buyOut=!e.isIntersecting&&e.boundingClientRect.top<0;upd();}).observe(buy);if(close)new IntersectionObserver(([e])=>{closeIn=e.isIntersecting;upd();}).observe(close);}
// projects show all
root.addEventListener('click',e=>{const b=e.target.closest('.agv-more');if(!b)return;const s=b.closest('.agv-projects');const on=!s.classList.contains('is-open');s.classList.toggle('is-open',on);b.setAttribute('aria-expanded',String(on));b.textContent=on?b.dataset.less:b.dataset.more;if(!on)s.scrollIntoView({behavior:'smooth'});});
// variation image -> first slide
if(window.jQuery)jQuery(document).on('found_variation','.agv form.variations_form',function(e,v){if(!v.image||!v.image.full_src||!slides[0])return;const im=slides[0].querySelector('img'),z=slides[0].querySelector('[data-full]');im.src=v.image.full_src;im.removeAttribute('srcset');if(z)z.dataset.full=v.image.full_src;const tg=slides[0].querySelector('.agv-tag');if(tg)tg.hidden=true;if(thumbs[0])thumbs[0].querySelector('img').src=v.image.gallery_thumbnail_src||v.image.full_src;go(0);});
})();
